# EX05

<div dir="rtl">
<img src="images/EX5_(1).png" alt="EX5_1">


In [10]:
keys = ["a", "b", "c"]
values = [1, 2, 3, 4, 5]


def ex5q1(keys, values):
    result = {}
    for i, k in enumerate(keys):
        if i < len(values):
            result[k] = values[i]
        else:
            result[k] = None

    return result


ex5q1(keys, values)

{'a': 1, 'b': 2, 'c': 3}

<div dir="rtl">
<img src="images/EX5_(2).png" alt="EX5_2">

In [ ]:
list_1 = [3, 1, 3, 2, 1, 4, 3]

def ex5q2(list_1):
    result = {}
    for i in list_1:
        if i in result:
            result[i] += 1
        else:
            result[i] = 1

    sorted_result = sorted(result.items(), key=lambda x: x[1], reverse=True)

    return dict(sorted_result)

ex5q2(list_1)

{3: 3, 1: 2, 2: 1, 4: 1}

In [ ]:
# using collections.Counter
from collections import Counter

list_1 = [3, 1, 3, 2, 1, 4, 3]

counting = Counter(list_1)

counting

Counter({3: 3, 1: 2, 2: 1, 4: 1})

<div dir="rtl">
<img src="images/EX5_(3).png" alt="EX5_3">


In [5]:
list_2 = {"sara": "CV", "ali": "ML", "mina": "ML"}

def ex5q3(list_2):
    result = {}

    for name, field in list_2.items():
        if field not in result:
            result[field] = []
        result[field].append(name)

    for field in result:
        result[field].sort()

    return result

ex5q3(list_2)

{'CV': ['sara'], 'ML': ['ali', 'mina']}

<div dir="rtl">
<img src="images/EX5_(4).png" alt="EX5_4">


In [6]:
A = {"a": {"x": 1, "y": 2}, "b": 0}
B = {"a": {"y": 9, "z": 3}, "c": 7}

def ex5q4(A, B):
    result = A.copy()
    for key, value in B.items():
        if key in result and isinstance(result[key], dict) and isinstance(value, dict):
            result[key] = ex5q4(result[key], value)
        else:
            result[key] = value
    return result

ex5q4(A, B)

{'a': {'x': 1, 'y': 9, 'z': 3}, 'b': 0, 'c': 7}

---

# EX06

### import numpy library

In [11]:
import numpy as np

<div dir="ltr">
<img src="images/EX6_(1).png" alt="EX6_1">

In [14]:
arr = np.arange(4*5*3)
arr2 = arr.reshape(4, 5, 3)

print(f'shape: {arr2.shape}')
print(f'dimension: {arr2.ndim}')
print(f'array: {arr2}')

shape: (4, 5, 3)
dimension: 3
array: [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]
  [12 13 14]]

 [[15 16 17]
  [18 19 20]
  [21 22 23]
  [24 25 26]
  [27 28 29]]

 [[30 31 32]
  [33 34 35]
  [36 37 38]
  [39 40 41]
  [42 43 44]]

 [[45 46 47]
  [48 49 50]
  [51 52 53]
  [54 55 56]
  [57 58 59]]]


<div dir="ltr">
<img src="images/EX6_(2).png" alt="EX6_2">

In [16]:
arr = arr.reshape(20, 3)

print(f'shape: {arr.shape}')
print(f'dimension: {arr.ndim}')
print(f'array: {arr}')

shape: (20, 3)
dimension: 2
array: [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]
 [24 25 26]
 [27 28 29]
 [30 31 32]
 [33 34 35]
 [36 37 38]
 [39 40 41]
 [42 43 44]
 [45 46 47]
 [48 49 50]
 [51 52 53]
 [54 55 56]
 [57 58 59]]


<div dir="ltr">
<img src="images/EX6_(3).png" alt="EX6_3">

In [17]:
arr = np.array([[10, 20, 30, 40], [50, 60, 70, 80]])

arr[1, 0]
print(arr[1:3,0:2])

[[50 60]]


<div dir="ltr">
<img src="images/EX6_(4).png" alt="EX6_4">

In [54]:
arr = np.array([[10, 20, 30, 40], [50, 60, 70, 80]])

arr = arr.astype(float)
print(arr)

[[10. 20. 30. 40.]
 [50. 60. 70. 80.]]


<div dir="ltr">
<img src="images/EX6_(5).png" alt="EX6_5">

In [26]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

result = np.concatenate((arr1, arr2))
print(result)

[1 2 3 4 5 6]


---